// @ts-nocheck
"use client";

import { useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api";

const months = [
  { value: 1, label: "April" },
  { value: 2, label: "May" },
  { value: 3, label: "June" },
  { value: 4, label: "July" },
  { value: 5, label: "August" },
  { value: 6, label: "September" },
  { value: 7, label: "October" },
  { value: 8, label: "November" },
  { value: 9, label: "December" },
  { value: 10, label: "January" },
  { value: 11, label: "February" },
  { value: 12, label: "March" },
];

export default function PaymentHistoryPage() {
  const [filterPeriod, setFilterPeriod] = useState<number | undefined>(undefined);
  const [filterYear, setFilterYear] = useState<number | undefined>(undefined);

  const { data: payments, isLoading } = api.gstPayment.paymentHistory.useQuery();

  const filteredPayments = payments?.filter((p) => {
    if (filterPeriod === undefined && filterYear === undefined) return true;
    const challanMonth = p.challanDate ? new Date(p.challanDate).getMonth() + 1 : null;
    const challanYear = p.challanDate ? new Date(p.challanDate).getFullYear() : null;
    
    if (filterPeriod !== undefined && challanMonth !== filterPeriod) return false;
    if (filterYear !== undefined && challanYear !== filterYear) return false;
    
    return true;
  });

  const handleDownloadChallan = (challan: any) => {
    const content = `
CHALLAN DETAILS
===============

Challan Number: ${challan.challanNumber}
Challan Date: ${challan.challanDate}
Payment Date: ${challan.paymentDate}
Bank: ${challan.bankName}

Tax Breakdown:
${challan.taxBreakdown.map((b: any) => `  ${b.taxType.toUpperCase()}: ₹${b.amount.toLocaleString("en-IN")}`).join("\n")}

Total Amount: ₹${challan.totalAmount.toLocaleString("en-IN")}

---
Generated by ComplianceOS
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${challan.challanNumber}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <Link href="/gst/ledger" className="text-sm text-gray-500 hover:underline">
            ← Back to GST Ledger
          </Link>
          <h1 className="text-2xl font-bold mt-1">Payment History</h1>
        </div>
        <Link 
          href="/gst/payment" 
          className="px-4 py-2 bg-blue-600 text-white text-sm rounded hover:bg-blue-700"
        >
          Make Payment
        </Link>
      </div>

      <div className="flex gap-4 items-center flex-wrap">
        <select
          value={filterPeriod ?? ""}
          onChange={(e) => setFilterPeriod(e.target.value ? Number(e.target.value) : undefined)}
          className="px-3 py-2 border rounded text-sm"
        >
          <option value="">All Months</option>
          {months.map((m) => (
            <option key={m.value} value={m.value}>{m.label}</option>
          ))}
        </select>

        <input
          type="number"
          placeholder="Year (e.g., 2026)"
          value={filterYear ?? ""}
          onChange={(e) => setFilterYear(e.target.value ? Number(e.target.value) : undefined)}
          className="px-3 py-2 border rounded text-sm w-32"
          min={2000}
          max={2100}
        />
      </div>

      <div className="bg-white rounded-lg shadow overflow-hidden">
        <div className="px-6 py-4 border-b">
          <h2 className="text-lg font-semibold">Challans</h2>
        </div>
        <table className="w-full text-sm">
          <thead className="bg-gray-50 border-b">
            <tr>
              <th className="px-4 py-3 text-left text-gray-500 font-medium">Challan #</th>
              <th className="px-4 py-3 text-left text-gray-500 font-medium">Challan Date</th>
              <th className="px-4 py-3 text-left text-gray-500 font-medium">Period</th>
              <th className="px-4 py-3 text-right text-gray-500 font-medium">Total Amount</th>
              <th className="px-4 py-3 text-left text-gray-500 font-medium">Payment Date</th>
              <th className="px-4 py-3 text-left text-gray-500 font-medium">Bank</th>
              <th className="px-4 py-3 text-left text-gray-500 font-medium">Tax Breakdown</th>
              <th className="px-4 py-3 text-left text-gray-500 font-medium">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y">
            {isLoading ? (
              <tr>
                <td colSpan={8} className="px-4 py-8 text-center text-gray-500">
                  Loading...
                </td>
              </tr>
            ) : filteredPayments && filteredPayments.length > 0 ? (
              filteredPayments.map((challan, idx) => (
                <tr key={challan.challanNumber || idx} className="hover:bg-gray-50">
                  <td className="px-4 py-3">
                    <span className="font-medium text-gray-900">{challan.challanNumber}</span>
                  </td>
                  <td className="px-4 py-3 text-gray-600">{challan.challanDate}</td>
                  <td className="px-4 py-3 text-gray-600">
                    {challan.narration?.match(/(\w+)\s+(\d{4})/)?.slice(1).join(" ") || "-"}
                  </td>
                  <td className="px-4 py-3 text-right font-medium text-gray-900">
                    ₹{challan.totalAmount.toLocaleString("en-IN")}
                  </td>
                  <td className="px-4 py-3 text-gray-600">{challan.paymentDate}</td>
                  <td className="px-4 py-3 text-gray-600">{challan.bankName || "-"}</td>
                  <td className="px-4 py-3">
                    <div className="flex gap-2 flex-wrap">
                      {challan.taxBreakdown.map((b: any, i: number) => (
                        <span key={i} className="px-2 py-1 text-xs rounded-full uppercase bg-gray-100 text-gray-800">
                          {b.taxType}: ₹{b.amount.toLocaleString("en-IN")}
                        </span>
                      ))}
                    </div>
                  </td>
                  <td className="px-4 py-3">
                    <button
                      onClick={() => handleDownloadChallan(challan)}
                      className="text-blue-600 hover:underline text-xs"
                    >
                      Download
                    </button>
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan={8} className="px-4 py-8 text-center text-gray-500">
                  No payment history yet
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {filteredPayments && filteredPayments.length > 0 && (
        <div className="text-sm text-gray-600">
          Showing {filteredPayments.length} challan(s)
        </div>
      )}
    </div>
  );
}
