import { z } from "zod";
export declare enum AdvanceTaxInstallmentNumber {
    INSTALLMENT_1 = "1",
    INSTALLMENT_2 = "2",
    INSTALLMENT_3 = "3",
    INSTALLMENT_4 = "4"
}
export declare const ADVANCE_TAX_DUE_DATES: Record<AdvanceTaxInstallmentNumber, string>;
export declare const RecordAdvanceTaxPaymentInputSchema: z.ZodObject<{
    assessmentYear: z.ZodString;
    installmentNumber: z.ZodNativeEnum<typeof AdvanceTaxInstallmentNumber>;
    paidAmount: z.ZodString;
    paidDate: z.ZodString;
    challanNumber: z.ZodString;
    challanDate: z.ZodString;
}, "strip", z.ZodTypeAny, {
    challanNumber?: string;
    challanDate?: string;
    assessmentYear?: string;
    installmentNumber?: AdvanceTaxInstallmentNumber;
    paidAmount?: string;
    paidDate?: string;
}, {
    challanNumber?: string;
    challanDate?: string;
    assessmentYear?: string;
    installmentNumber?: AdvanceTaxInstallmentNumber;
    paidAmount?: string;
    paidDate?: string;
}>;
export type RecordAdvanceTaxPaymentInput = z.infer<typeof RecordAdvanceTaxPaymentInputSchema>;
export declare const RecordSelfAssessmentTaxInputSchema: z.ZodObject<{
    assessmentYear: z.ZodString;
    taxPayable: z.ZodString;
    advanceTaxPaid: z.ZodString;
    tdsTcsCredit: z.ZodString;
    balancePayable: z.ZodString;
    paidAmount: z.ZodOptional<z.ZodString>;
    challanNumber: z.ZodOptional<z.ZodString>;
    challanDate: z.ZodOptional<z.ZodString>;
    paidDate: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    challanNumber?: string;
    challanDate?: string;
    taxPayable?: string;
    assessmentYear?: string;
    advanceTaxPaid?: string;
    tdsTcsCredit?: string;
    balancePayable?: string;
    paidAmount?: string;
    paidDate?: string;
}, {
    challanNumber?: string;
    challanDate?: string;
    taxPayable?: string;
    assessmentYear?: string;
    advanceTaxPaid?: string;
    tdsTcsCredit?: string;
    balancePayable?: string;
    paidAmount?: string;
    paidDate?: string;
}>;
export type RecordSelfAssessmentTaxInput = z.infer<typeof RecordSelfAssessmentTaxInputSchema>;
export declare const AdvanceTaxInstallmentSchema: z.ZodObject<{
    id: z.ZodString;
    tenantId: z.ZodString;
    assessmentYear: z.ZodString;
    installmentNumber: z.ZodString;
    dueDate: z.ZodString;
    payableAmount: z.ZodString;
    paidAmount: z.ZodString;
    paidDate: z.ZodNullable<z.ZodString>;
    challanNumber: z.ZodNullable<z.ZodString>;
    challanDate: z.ZodNullable<z.ZodString>;
    interest234b: z.ZodString;
    interest234c: z.ZodString;
    balance: z.ZodString;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    tenantId?: string;
    id?: string;
    createdAt?: Date;
    dueDate?: string;
    balance?: string;
    challanNumber?: string;
    challanDate?: string;
    assessmentYear?: string;
    installmentNumber?: string;
    payableAmount?: string;
    paidAmount?: string;
    paidDate?: string;
    interest234b?: string;
    interest234c?: string;
}, {
    tenantId?: string;
    id?: string;
    createdAt?: Date;
    dueDate?: string;
    balance?: string;
    challanNumber?: string;
    challanDate?: string;
    assessmentYear?: string;
    installmentNumber?: string;
    payableAmount?: string;
    paidAmount?: string;
    paidDate?: string;
    interest234b?: string;
    interest234c?: string;
}>;
export type AdvanceTaxInstallment = z.infer<typeof AdvanceTaxInstallmentSchema>;
export declare const AdvanceTaxLedgerSchema: z.ZodObject<{
    assessmentYear: z.ZodString;
    installments: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        tenantId: z.ZodString;
        assessmentYear: z.ZodString;
        installmentNumber: z.ZodString;
        dueDate: z.ZodString;
        payableAmount: z.ZodString;
        paidAmount: z.ZodString;
        paidDate: z.ZodNullable<z.ZodString>;
        challanNumber: z.ZodNullable<z.ZodString>;
        challanDate: z.ZodNullable<z.ZodString>;
        interest234b: z.ZodString;
        interest234c: z.ZodString;
        balance: z.ZodString;
        createdAt: z.ZodDate;
    }, "strip", z.ZodTypeAny, {
        tenantId?: string;
        id?: string;
        createdAt?: Date;
        dueDate?: string;
        balance?: string;
        challanNumber?: string;
        challanDate?: string;
        assessmentYear?: string;
        installmentNumber?: string;
        payableAmount?: string;
        paidAmount?: string;
        paidDate?: string;
        interest234b?: string;
        interest234c?: string;
    }, {
        tenantId?: string;
        id?: string;
        createdAt?: Date;
        dueDate?: string;
        balance?: string;
        challanNumber?: string;
        challanDate?: string;
        assessmentYear?: string;
        installmentNumber?: string;
        payableAmount?: string;
        paidAmount?: string;
        paidDate?: string;
        interest234b?: string;
        interest234c?: string;
    }>, "many">;
    totalPayable: z.ZodString;
    totalPaid: z.ZodString;
    totalBalance: z.ZodString;
    totalInterest234b: z.ZodString;
    totalInterest234c: z.ZodString;
}, "strip", z.ZodTypeAny, {
    installments?: {
        tenantId?: string;
        id?: string;
        createdAt?: Date;
        dueDate?: string;
        balance?: string;
        challanNumber?: string;
        challanDate?: string;
        assessmentYear?: string;
        installmentNumber?: string;
        payableAmount?: string;
        paidAmount?: string;
        paidDate?: string;
        interest234b?: string;
        interest234c?: string;
    }[];
    assessmentYear?: string;
    totalPayable?: string;
    totalPaid?: string;
    totalBalance?: string;
    totalInterest234b?: string;
    totalInterest234c?: string;
}, {
    installments?: {
        tenantId?: string;
        id?: string;
        createdAt?: Date;
        dueDate?: string;
        balance?: string;
        challanNumber?: string;
        challanDate?: string;
        assessmentYear?: string;
        installmentNumber?: string;
        payableAmount?: string;
        paidAmount?: string;
        paidDate?: string;
        interest234b?: string;
        interest234c?: string;
    }[];
    assessmentYear?: string;
    totalPayable?: string;
    totalPaid?: string;
    totalBalance?: string;
    totalInterest234b?: string;
    totalInterest234c?: string;
}>;
export type AdvanceTaxLedger = z.infer<typeof AdvanceTaxLedgerSchema>;
export declare const SelfAssessmentTaxSchema: z.ZodObject<{
    id: z.ZodString;
    tenantId: z.ZodString;
    assessmentYear: z.ZodString;
    taxPayable: z.ZodString;
    advanceTaxPaid: z.ZodString;
    tdsTcsCredit: z.ZodString;
    balancePayable: z.ZodString;
    paidAmount: z.ZodString;
    challanNumber: z.ZodNullable<z.ZodString>;
    challanDate: z.ZodNullable<z.ZodString>;
    paidDate: z.ZodNullable<z.ZodString>;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    tenantId?: string;
    id?: string;
    createdAt?: Date;
    challanNumber?: string;
    challanDate?: string;
    taxPayable?: string;
    assessmentYear?: string;
    advanceTaxPaid?: string;
    tdsTcsCredit?: string;
    balancePayable?: string;
    paidAmount?: string;
    paidDate?: string;
}, {
    tenantId?: string;
    id?: string;
    createdAt?: Date;
    challanNumber?: string;
    challanDate?: string;
    taxPayable?: string;
    assessmentYear?: string;
    advanceTaxPaid?: string;
    tdsTcsCredit?: string;
    balancePayable?: string;
    paidAmount?: string;
    paidDate?: string;
}>;
export type SelfAssessmentTax = z.infer<typeof SelfAssessmentTaxSchema>;
export declare const SelfAssessmentLedgerSchema: z.ZodObject<{
    assessmentYear: z.ZodString;
    taxPayable: z.ZodString;
    advanceTaxPaid: z.ZodString;
    tdsTcsCredit: z.ZodString;
    balancePayable: z.ZodString;
    paidAmount: z.ZodString;
    challanNumber: z.ZodNullable<z.ZodString>;
    challanDate: z.ZodNullable<z.ZodString>;
    paidDate: z.ZodNullable<z.ZodString>;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    createdAt?: Date;
    challanNumber?: string;
    challanDate?: string;
    taxPayable?: string;
    assessmentYear?: string;
    advanceTaxPaid?: string;
    tdsTcsCredit?: string;
    balancePayable?: string;
    paidAmount?: string;
    paidDate?: string;
}, {
    createdAt?: Date;
    challanNumber?: string;
    challanDate?: string;
    taxPayable?: string;
    assessmentYear?: string;
    advanceTaxPaid?: string;
    tdsTcsCredit?: string;
    balancePayable?: string;
    paidAmount?: string;
    paidDate?: string;
}>;
export type SelfAssessmentLedger = z.infer<typeof SelfAssessmentLedgerSchema>;
export declare const ITRTaxLedgerSummarySchema: z.ZodObject<{
    assessmentYear: z.ZodString;
    advanceTax: z.ZodObject<{
        assessmentYear: z.ZodString;
        installments: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            tenantId: z.ZodString;
            assessmentYear: z.ZodString;
            installmentNumber: z.ZodString;
            dueDate: z.ZodString;
            payableAmount: z.ZodString;
            paidAmount: z.ZodString;
            paidDate: z.ZodNullable<z.ZodString>;
            challanNumber: z.ZodNullable<z.ZodString>;
            challanDate: z.ZodNullable<z.ZodString>;
            interest234b: z.ZodString;
            interest234c: z.ZodString;
            balance: z.ZodString;
            createdAt: z.ZodDate;
        }, "strip", z.ZodTypeAny, {
            tenantId?: string;
            id?: string;
            createdAt?: Date;
            dueDate?: string;
            balance?: string;
            challanNumber?: string;
            challanDate?: string;
            assessmentYear?: string;
            installmentNumber?: string;
            payableAmount?: string;
            paidAmount?: string;
            paidDate?: string;
            interest234b?: string;
            interest234c?: string;
        }, {
            tenantId?: string;
            id?: string;
            createdAt?: Date;
            dueDate?: string;
            balance?: string;
            challanNumber?: string;
            challanDate?: string;
            assessmentYear?: string;
            installmentNumber?: string;
            payableAmount?: string;
            paidAmount?: string;
            paidDate?: string;
            interest234b?: string;
            interest234c?: string;
        }>, "many">;
        totalPayable: z.ZodString;
        totalPaid: z.ZodString;
        totalBalance: z.ZodString;
        totalInterest234b: z.ZodString;
        totalInterest234c: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        installments?: {
            tenantId?: string;
            id?: string;
            createdAt?: Date;
            dueDate?: string;
            balance?: string;
            challanNumber?: string;
            challanDate?: string;
            assessmentYear?: string;
            installmentNumber?: string;
            payableAmount?: string;
            paidAmount?: string;
            paidDate?: string;
            interest234b?: string;
            interest234c?: string;
        }[];
        assessmentYear?: string;
        totalPayable?: string;
        totalPaid?: string;
        totalBalance?: string;
        totalInterest234b?: string;
        totalInterest234c?: string;
    }, {
        installments?: {
            tenantId?: string;
            id?: string;
            createdAt?: Date;
            dueDate?: string;
            balance?: string;
            challanNumber?: string;
            challanDate?: string;
            assessmentYear?: string;
            installmentNumber?: string;
            payableAmount?: string;
            paidAmount?: string;
            paidDate?: string;
            interest234b?: string;
            interest234c?: string;
        }[];
        assessmentYear?: string;
        totalPayable?: string;
        totalPaid?: string;
        totalBalance?: string;
        totalInterest234b?: string;
        totalInterest234c?: string;
    }>;
    selfAssessment: z.ZodObject<{
        assessmentYear: z.ZodString;
        taxPayable: z.ZodString;
        advanceTaxPaid: z.ZodString;
        tdsTcsCredit: z.ZodString;
        balancePayable: z.ZodString;
        paidAmount: z.ZodString;
        challanNumber: z.ZodNullable<z.ZodString>;
        challanDate: z.ZodNullable<z.ZodString>;
        paidDate: z.ZodNullable<z.ZodString>;
        createdAt: z.ZodDate;
    }, "strip", z.ZodTypeAny, {
        createdAt?: Date;
        challanNumber?: string;
        challanDate?: string;
        taxPayable?: string;
        assessmentYear?: string;
        advanceTaxPaid?: string;
        tdsTcsCredit?: string;
        balancePayable?: string;
        paidAmount?: string;
        paidDate?: string;
    }, {
        createdAt?: Date;
        challanNumber?: string;
        challanDate?: string;
        taxPayable?: string;
        assessmentYear?: string;
        advanceTaxPaid?: string;
        tdsTcsCredit?: string;
        balancePayable?: string;
        paidAmount?: string;
        paidDate?: string;
    }>;
    totalTaxPaid: z.ZodString;
    totalBalance: z.ZodString;
    totalInterest: z.ZodString;
}, "strip", z.ZodTypeAny, {
    totalTaxPaid?: string;
    assessmentYear?: string;
    advanceTax?: {
        installments?: {
            tenantId?: string;
            id?: string;
            createdAt?: Date;
            dueDate?: string;
            balance?: string;
            challanNumber?: string;
            challanDate?: string;
            assessmentYear?: string;
            installmentNumber?: string;
            payableAmount?: string;
            paidAmount?: string;
            paidDate?: string;
            interest234b?: string;
            interest234c?: string;
        }[];
        assessmentYear?: string;
        totalPayable?: string;
        totalPaid?: string;
        totalBalance?: string;
        totalInterest234b?: string;
        totalInterest234c?: string;
    };
    totalBalance?: string;
    selfAssessment?: {
        createdAt?: Date;
        challanNumber?: string;
        challanDate?: string;
        taxPayable?: string;
        assessmentYear?: string;
        advanceTaxPaid?: string;
        tdsTcsCredit?: string;
        balancePayable?: string;
        paidAmount?: string;
        paidDate?: string;
    };
    totalInterest?: string;
}, {
    totalTaxPaid?: string;
    assessmentYear?: string;
    advanceTax?: {
        installments?: {
            tenantId?: string;
            id?: string;
            createdAt?: Date;
            dueDate?: string;
            balance?: string;
            challanNumber?: string;
            challanDate?: string;
            assessmentYear?: string;
            installmentNumber?: string;
            payableAmount?: string;
            paidAmount?: string;
            paidDate?: string;
            interest234b?: string;
            interest234c?: string;
        }[];
        assessmentYear?: string;
        totalPayable?: string;
        totalPaid?: string;
        totalBalance?: string;
        totalInterest234b?: string;
        totalInterest234c?: string;
    };
    totalBalance?: string;
    selfAssessment?: {
        createdAt?: Date;
        challanNumber?: string;
        challanDate?: string;
        taxPayable?: string;
        assessmentYear?: string;
        advanceTaxPaid?: string;
        tdsTcsCredit?: string;
        balancePayable?: string;
        paidAmount?: string;
        paidDate?: string;
    };
    totalInterest?: string;
}>;
export type ITRTaxLedgerSummary = z.infer<typeof ITRTaxLedgerSummarySchema>;
export declare const AdvanceTaxPaidPayloadSchema: z.ZodObject<{
    aggregateId: z.ZodString;
    installmentId: z.ZodString;
    tenantId: z.ZodString;
    assessmentYear: z.ZodString;
    installmentNumber: z.ZodString;
    amount: z.ZodNumber;
    challanNumber: z.ZodString;
    challanDate: z.ZodString;
    interest234C: z.ZodOptional<z.ZodNumber>;
    paidAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    tenantId?: string;
    aggregateId?: string;
    paidAt?: Date;
    amount?: number;
    challanNumber?: string;
    challanDate?: string;
    assessmentYear?: string;
    installmentNumber?: string;
    installmentId?: string;
    interest234C?: number;
}, {
    tenantId?: string;
    aggregateId?: string;
    paidAt?: Date;
    amount?: number;
    challanNumber?: string;
    challanDate?: string;
    assessmentYear?: string;
    installmentNumber?: string;
    installmentId?: string;
    interest234C?: number;
}>;
export type AdvanceTaxPaidPayload = z.infer<typeof AdvanceTaxPaidPayloadSchema>;
export declare const SelfAssessmentTaxPaidPayloadSchema: z.ZodObject<{
    aggregateId: z.ZodString;
    paymentId: z.ZodString;
    tenantId: z.ZodString;
    assessmentYear: z.ZodString;
    itrReturnId: z.ZodString;
    amount: z.ZodNumber;
    challanNumber: z.ZodString;
    challanDate: z.ZodString;
    balanceAfterPayment: z.ZodNumber;
    paidAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    tenantId?: string;
    aggregateId?: string;
    paidAt?: Date;
    amount?: number;
    paymentId?: string;
    challanNumber?: string;
    challanDate?: string;
    assessmentYear?: string;
    itrReturnId?: string;
    balanceAfterPayment?: number;
}, {
    tenantId?: string;
    aggregateId?: string;
    paidAt?: Date;
    amount?: number;
    paymentId?: string;
    challanNumber?: string;
    challanDate?: string;
    assessmentYear?: string;
    itrReturnId?: string;
    balanceAfterPayment?: number;
}>;
export type SelfAssessmentTaxPaidPayload = z.infer<typeof SelfAssessmentTaxPaidPayloadSchema>;
//# sourceMappingURL=itr-ledgers.d.ts.map