import {
  LayoutDashboard,
  BookOpen,
  TreePine,
  Receipt,
  Wallet,
  Gavel,
  ScrollText,
  Package,
  Users,
  Settings,
  HelpCircle,
  LogOut,
  Search,
  Bell,
  Plus,
  CircleDot,
  Circle,
  PlusCircle,
  MinusCircle,
  Trash2,
  Edit3,
  X,
  Check,
  CheckCircle,
  Download,
  Upload,
  Share2,
  Printer,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  AlertTriangle,
  XCircle,
  Info,
  Shield,
  History,
  Clock,
  Ban,
  FileBarChart,
  TrendingUp,
  DollarSign,
  Scale,
  Calendar,
  Filter,
  Inbox,
  RefreshCw,
  RotateCcw,
  Eye,
  EyeOff,
  MoreHorizontal,
  MoreVertical,
  Sun,
  Moon,
  Monitor,
  Languages,
  User,
  UserPlus,
  FolderOpen,
  Folder,
  List,
  ArrowLeftRight,
  Calculator,
  Truck,
  Warehouse,
  LayoutList,
  Mail,
  Phone,
  MessageCircle,
  ExternalLink,
  Bug,
  Code2,
  type LucideIcon,
} from 'lucide-react';

export type IconName = keyof typeof iconMap;

const iconMap: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  menu_book: BookOpen,
  account_tree: TreePine,
  receipt_long: Receipt,
  account_balance_wallet: Wallet,
  gavel: Gavel,
  description: ScrollText,
  inventory_2: Package,
  group: Users,
  groups: Users,
  payments: Wallet,
  settings: Settings,
  contact_support: HelpCircle,
  logout: LogOut,
  search: Search,
  notifications: Bell,
  add: Plus,
  radio_button_checked: CircleDot,
  radio_button_unchecked: Circle,
  add_circle: PlusCircle,
  remove: MinusCircle,
  delete: Trash2,
  edit: Edit3,
  close: X,
  done: Check,
  check: Check,
  check_circle: CheckCircle,
  download: Download,
  upload: Upload,
  upload_file: Upload,
  share: Share2,
  print: Printer,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  chevron_down: ChevronDown,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  arrow_downward: ArrowDown,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  warning: AlertTriangle,
  error: XCircle,
  info: Info,
  help_outline: HelpCircle,
  verified: Shield,
  verified_user: Shield,
  security: Shield,
  history: History,
  clock: Clock,
  cancel: Ban,
  insert_chart: FileBarChart,
  trending_up: TrendingUp,
  assessment: FileBarChart,
  analytics: TrendingUp,
  account_balance: DollarSign,
  scale: Scale,
  calendar: Calendar,
  calendar_month: Calendar,
  filter_list: Filter,
  inbox: Inbox,
  refresh: RefreshCw,
  update: RefreshCw,
  sync_alt: RotateCcw,
  visibility: Eye,
  visibility_off: EyeOff,
  search_off: XCircle,
  more_horiz: MoreHorizontal,
  more_vert: MoreVertical,
  light_mode: Sun,
  dark_mode: Moon,
  brightness_auto: Monitor,
  translate: Languages,
  // Added for sidebar nav and topbar
  person: User,
  person_add: UserPlus,
  folder_open: FolderOpen,
  folder: Folder,
  list: List,
  compare_arrows: ArrowLeftRight,
  calculate: Calculator,
  inventory: Package,
  local_shipping: Truck,
  warehouse: Warehouse,
  list_alt: LayoutList,
  mail: Mail,
  phone: Phone,
  chat: MessageCircle,
  open_in_new: ExternalLink,
  bug_report: Bug,
  code: Code2,
};

export { iconMap };

export function Icon({ name, className, size = 24 }: { name: string; className?: string; size?: number }) {
  const LucideIcon = iconMap[name];
  if (!LucideIcon) return <span className={className} style={{ width: size, height: size }} />;
  return <LucideIcon className={className} size={size} />;
}
