"use client";

import { useEffect, useState } from "react";
import { Icon } from "@/components/ui/icon";
import { showToast } from "@/lib/toast";
import { useFiscalYear } from "@/hooks/use-fiscal-year";
import { api } from "@/lib/api";
import { PageHeader } from "@/components/ui/page-header";

export default function InvoiceConfigPage() {
  const { activeFy } = useFiscalYear();
  const utils = api.useUtils();

  const [prefix, setPrefix] = useState("");
  const [companyAddress, setCompanyAddress] = useState("");
  const [bankName, setBankName] = useState("");
  const [bankIfsc, setBankIfsc] = useState("");
  const [bankAccount, setBankAccount] = useState("");
  const [logoUrl, setLogoUrl] = useState<string | null>(null);
  const [logoPreview, setLogoPreview] = useState<string | null>(null);

  const config = api.invoiceConfig.get.useQuery(undefined, { staleTime: 15_000 });

  useEffect(() => {
    if (!config.data) return;
    const c = config.data;
    const bd = (c.bankDetails ?? {}) as { bankName?: string; ifsc?: string; accountNumber?: string };
    setPrefix(c.prefix ?? "");
    setCompanyAddress(c.companyAddress ?? "");
    setBankName(bd.bankName ?? "");
    setBankIfsc(bd.ifsc ?? "");
    setBankAccount(bd.accountNumber ?? "");
    setLogoUrl(c.logoUrl ?? null);
    setLogoPreview(c.logoUrl ?? null);
  }, [config.data]);

  const save = api.invoiceConfig.save.useMutation({
    onSuccess: () => {
      showToast.success("Invoice settings saved.");
      void utils.invoiceConfig.get.invalidate();
    },
    onError: (e) => showToast.error(e.message),
  });

  const onLogoFile = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      const dataUrl = String(reader.result);
      setLogoPreview(dataUrl);
      setLogoUrl(dataUrl);
    };
    reader.readAsDataURL(file);
  };

  const handleSave = () => {
    save.mutate({
      prefix: prefix.trim() || "INV",
      companyAddress: companyAddress.trim() || undefined,
      logoUrl: logoUrl ?? undefined,
      bankDetails: {
        bankName: bankName.trim() || undefined,
        ifsc: bankIfsc.trim() || undefined,
        accountNumber: bankAccount.trim() || undefined,
      },
    });
  };

  return (
    <div className="space-y-0 text-left">
      {/* Sticky Header */}
      <header className="sticky top-0 z-30 bg-page-bg/90 backdrop-blur-md border-b-[0.5px] border-border px-8 py-8 flex justify-between items-end -mx-8 -mt-8 mb-8">
        <div>
          <p className="font-ui text-ui-2xs text-amber uppercase tracking-widest mb-2 font-bold">Workspace Configuration · FY {activeFy}</p>
          <PageHeader title="Invoice Settings" />
          <p className="text-ui-sm text-secondary font-ui mt-1">Define document prefixes, statutory disclosures, and bank account mappings.</p>
        </div>
        <div className="flex gap-4">
          <button onClick={handleSave} disabled={save.isPending || config.isLoading} className="btn btn-primary disabled:opacity-50">
            {save.isPending ? "Saving…" : "Save Changes"}
          </button>
        </div>
      </header>

      <div className="max-w-4xl mx-auto space-y-12 pb-12">
        {/* Section 1: Naming & Sequence */}
        <section className="bg-surface border border-border p-8 shadow-sm">
          <h3 className="font-ui text-lg font-bold text-dark mb-6">Naming & Sequence</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="flex flex-col gap-2">
              <label htmlFor="invoice-prefix" className="font-ui text-ui-2xs text-mid uppercase tracking-widest font-bold">Invoice Prefix</label>
              <input id="invoice-prefix" className="w-full bg-surface-muted border border-border rounded-md px-4 py-3 font-mono text-sm text-dark focus:border-primary outline-none focus-visible:ring-2 focus-visible:ring-focus focus-visible:ring-offset-2 focus-visible:ring-offset-surface" value={prefix} onChange={(e) => setPrefix(e.target.value)} placeholder="INV" />
              <p className="text-ui-2xs text-light italic">Example: INV-0001. The running number is generated by the server.</p>
            </div>
          </div>
        </section>

        {/* Section 2: Statutory & Branding */}
        <section className="bg-surface border border-border p-8 shadow-sm">
          <h3 className="font-ui text-lg font-bold text-dark mb-6">Statutory & Branding</h3>
          <div className="space-y-8">
            <div className="flex flex-col gap-2">
              <label htmlFor="invoice-address" className="font-ui text-ui-2xs text-mid uppercase tracking-widest font-bold">Invoice Header Address</label>
              <textarea id="invoice-address" className="w-full bg-surface-muted border border-border rounded-md px-4 py-3 font-ui text-ui-sm text-dark focus:border-primary outline-none focus-visible:ring-2 focus-visible:ring-focus focus-visible:ring-offset-2 focus-visible:ring-offset-surface resize-none" rows={3} value={companyAddress} onChange={(e) => setCompanyAddress(e.target.value)} placeholder="Registered office address" />
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="flex flex-col gap-2">
                <label className="font-ui text-ui-2xs text-mid uppercase tracking-widest font-bold">Logo (B&W Recommended)</label>
                <label className="border-2 border-dashed border-border-strong p-6 flex flex-col items-center justify-center bg-surface-muted transition-colors cursor-pointer hover:bg-surface-muted">
                  {logoPreview ? (
                    <img src={logoPreview} alt="Invoice logo preview" className="max-h-20 mb-2 object-contain" />
                  ) : (
                    <Icon name="upload_file" className="text-light text-3xl mb-2" />
                  )}
                  <span className="font-ui text-ui-2xs uppercase font-bold text-mid">{logoPreview ? "Replace logo" : "Upload PNG/JPG"}</span>
                  <input type="file" accept="image/png,image/jpeg" onChange={onLogoFile} className="sr-only" aria-label="Upload invoice logo" />
                </label>
                <p className="text-ui-2xs text-light italic">Stored with the tenant config; used in the invoice PDF header.</p>
              </div>
            </div>
          </div>
        </section>

        {/* Section 3: Bank Details */}
        <section className="bg-surface border border-border p-8 shadow-sm">
          <h3 className="font-ui text-lg font-bold text-dark mb-6">Payment & Bank Details</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-6">
            <div className="flex flex-col gap-2">
              <label htmlFor="bank-name" className="font-ui text-ui-2xs text-mid uppercase tracking-widest font-bold">Bank Name</label>
              <input id="bank-name" className="w-full bg-surface-muted border border-border rounded-md px-4 py-3 font-ui text-ui-sm text-dark focus:border-primary outline-none focus-visible:ring-2 focus-visible:ring-focus focus-visible:ring-offset-2 focus-visible:ring-offset-surface" value={bankName} onChange={(e) => setBankName(e.target.value)} />
            </div>
            <div className="flex flex-col gap-2">
              <label htmlFor="bank-ifsc" className="font-ui text-ui-2xs text-mid uppercase tracking-widest font-bold">IFSC Code</label>
              <input id="bank-ifsc" className="w-full bg-surface-muted border border-border rounded-md px-4 py-3 font-mono text-sm text-dark focus:border-primary outline-none focus-visible:ring-2 focus-visible:ring-focus focus-visible:ring-offset-2 focus-visible:ring-offset-surface" value={bankIfsc} onChange={(e) => setBankIfsc(e.target.value)} />
            </div>
            <div className="flex flex-col gap-2 md:col-span-2">
              <label htmlFor="bank-account" className="font-ui text-ui-2xs text-mid uppercase tracking-widest font-bold">Account Number</label>
              <input id="bank-account" className="w-full bg-surface-muted border border-border rounded-md px-4 py-3 font-mono text-sm text-dark focus:border-primary outline-none focus-visible:ring-2 focus-visible:ring-focus focus-visible:ring-offset-2 focus-visible:ring-offset-surface" value={bankAccount} onChange={(e) => setBankAccount(e.target.value)} />
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
