export declare const businessTypeEnum: import("drizzle-orm/pg-core").PgEnum<["sole_proprietorship", "partnership", "llp", "private_limited", "public_limited", "huf"]>;
export declare const stateEnum: import("drizzle-orm/pg-core").PgEnum<["andhra_pradesh", "arunachal_pradesh", "assam", "bihar", "chhattisgarh", "goa", "gujarat", "haryana", "himachal_pradesh", "jharkhand", "karnataka", "kerala", "madhya_pradesh", "maharashtra", "manipur", "meghalaya", "mizoram", "nagaland", "odisha", "punjab", "rajasthan", "sikkim", "tamil_nadu", "telangana", "tripura", "uttar_pradesh", "uttarakhand", "west_bengal", "andaman_nicobar", "chandigarh", "dadra_nagar_haveli_daman_diu", "delhi", "jammu_kashmir", "ladakh", "lakshadweep", "puducherry"]>;
export declare const industryEnum: import("drizzle-orm/pg-core").PgEnum<["retail_trading", "manufacturing", "services_professional", "freelancer_consultant", "regulated_professional"]>;
export declare const gstRegistrationEnum: import("drizzle-orm/pg-core").PgEnum<["regular", "composition", "none"]>;
export declare const roleEnum: import("drizzle-orm/pg-core").PgEnum<["owner", "accountant", "manager", "employee"]>;
export declare const moduleEnum: import("drizzle-orm/pg-core").PgEnum<["accounting", "invoicing", "inventory", "payroll", "gst", "ocr", "itr"]>;
export declare const setByEnum: import("drizzle-orm/pg-core").PgEnum<["auto", "manual"]>;
export declare const accountKindEnum: import("drizzle-orm/pg-core").PgEnum<["Asset", "Liability", "Equity", "Revenue", "Expense"]>;
export declare const accountSubTypeEnum: import("drizzle-orm/pg-core").PgEnum<["CurrentAsset", "FixedAsset", "Bank", "Cash", "Inventory", "CurrentLiability", "LongTermLiability", "Capital", "Drawing", "Reserves", "OperatingRevenue", "OtherRevenue", "DirectExpense", "IndirectExpense"]>;
export declare const tagEnum: import("drizzle-orm/pg-core").PgEnum<["trade_receivable", "trade_payable", "gst", "tds", "tds_payable", "finance_cost", "depreciation", "tax", "employee_benefits", "manufacturing", "inventory_adjustment", "trading", "returns", "opening_balance"]>;
export declare const reconciliationAccountEnum: import("drizzle-orm/pg-core").PgEnum<["bank", "none"]>;
export declare const referenceTypeEnum: import("drizzle-orm/pg-core").PgEnum<["invoice", "payment", "receipt", "journal", "payroll", "inventory", "opening_balance", "manual"]>;
export declare const jeStatusEnum: import("drizzle-orm/pg-core").PgEnum<["draft", "posted", "voided"]>;
export declare const aggregateTypeEnum: import("drizzle-orm/pg-core").PgEnum<["journal_entry", "account", "fiscal_year", "invoice", "credit_note", "payment", "payroll_run", "salary_structure", "employee_advance", "gst_challan", "gst_payment", "gst_return", "itr_return"]>;
export declare const eventTypeEnum: import("drizzle-orm/pg-core").PgEnum<["journal_entry_created", "journal_entry_modified", "journal_entry_deleted", "journal_entry_posted", "journal_entry_voided", "journal_entry_reversed", "account_created", "account_modified", "account_deactivated", "fiscal_year_created", "fiscal_year_closed", "narration_corrected", "invoice_created", "invoice_modified", "invoice_deleted", "invoice_posted", "invoice_voided", "invoice_sent", "credit_note_created", "credit_note_modified", "credit_note_issued", "credit_note_voided", "payment_recorded", "payment_voided", "employee_created", "employee_updated", "employee_deactivated", "salary_structure_created", "salary_structure_updated", "payroll_processed", "payroll_finalized", "payroll_voided", "payslip_generated", "advance_given", "advance_recovered", "gst_challan_created", "gst_payment_made", "itc_reconciled", "itc_utilized", "purchase_posted", "purchase_voided", "itc_reversed", "gst_refund_claimed", "gstr3b_generated", "income_computed", "tax_computed", "itr_generated"]>;
export declare const cashFlowCategoryEnum: import("drizzle-orm/pg-core").PgEnum<["operating", "investing", "financing"]>;
export declare const fyStatusEnum: import("drizzle-orm/pg-core").PgEnum<["open", "closed"]>;
export declare const ocrScanTypeEnum: import("drizzle-orm/pg-core").PgEnum<["invoice", "receipt"]>;
export declare const invoiceStatusEnum: import("drizzle-orm/pg-core").PgEnum<["draft", "sent", "partially_paid", "paid", "voided"]>;
export declare const paymentMethodEnum: import("drizzle-orm/pg-core").PgEnum<["cash", "bank", "online", "cheque"]>;
export declare const paymentStatusEnum: import("drizzle-orm/pg-core").PgEnum<["recorded", "voided"]>;
export declare const creditNoteStatusEnum: import("drizzle-orm/pg-core").PgEnum<["draft", "issued", "voided"]>;
export declare const ocrStatusEnum: import("drizzle-orm/pg-core").PgEnum<["pending", "processing", "completed", "failed", "converted"]>;
export declare const stockMovementTypeEnum: import("drizzle-orm/pg-core").PgEnum<["purchase_receipt", "sales_delivery", "stock_adjustment", "warehouse_transfer", "opening_balance"]>;
export declare const valuationMethodEnum: import("drizzle-orm/pg-core").PgEnum<["fifo", "weighted_average"]>;
export declare const payrollRunStatusEnum: import("drizzle-orm/pg-core").PgEnum<["draft", "processing", "calculated", "finalized", "voided", "failed"]>;
export declare const payrollComponentTypeEnum: import("drizzle-orm/pg-core").PgEnum<["earning", "deduction", "statutory", "advance", "arrears"]>;
export declare const tdsRegimeEnum: import("drizzle-orm/pg-core").PgEnum<["old", "new"]>;
export declare const advanceStatusEnum: import("drizzle-orm/pg-core").PgEnum<["active", "fully_recovered", "cancelled"]>;
export declare const employeeStatusEnum: import("drizzle-orm/pg-core").PgEnum<["active", "inactive", "exited"]>;
export declare const genderEnum: import("drizzle-orm/pg-core").PgEnum<["male", "female", "other"]>;
export declare const documentTypeEnum: import("drizzle-orm/pg-core").PgEnum<["pan_card", "aadhaar_card", "photo", "bank_proof", "uan_card", "esi_card", "address_proof", "qualification_certificate", "experience_letter"]>;
export declare const gstReturnTypeEnum: import("drizzle-orm/pg-core").PgEnum<["gstr1", "gstr2b", "gstr3b", "gstr9", "gstr4", "itc_reconciliation"]>;
export declare const gstReturnStatusEnum: import("drizzle-orm/pg-core").PgEnum<["draft", "generated", "filed", "amended", "completed"]>;
export declare const gstTaxTypeEnum: import("drizzle-orm/pg-core").PgEnum<["igst", "cgst", "sgst", "cess"]>;
export declare const gstTransactionTypeEnum: import("drizzle-orm/pg-core").PgEnum<["payment", "interest", "penalty", "refund", "itc_utilization"]>;
export declare const itrReturnTypeEnum: import("drizzle-orm/pg-core").PgEnum<["itr3", "itr4", "itr5", "itr1", "itr2"]>;
export declare const itrReturnStatusEnum: import("drizzle-orm/pg-core").PgEnum<["draft", "computed", "generated", "filed", "verified", "voided"]>;
export declare const incomeHeadEnum: import("drizzle-orm/pg-core").PgEnum<["salary", "house_property", "business_profit", "capital_gains", "other_sources"]>;
export declare const taxRegimeEnum: import("drizzle-orm/pg-core").PgEnum<["old", "new"]>;
export declare const presumptiveSchemeEnum: import("drizzle-orm/pg-core").PgEnum<["44ad", "44ada", "44ae", "none"]>;
//# sourceMappingURL=enums.d.ts.map