export declare const eventStore: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "event_store";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "event_store";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        tenantId: import("drizzle-orm/pg-core").PgColumn<{
            name: "tenant_id";
            tableName: "event_store";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        aggregateType: import("drizzle-orm/pg-core").PgColumn<{
            name: "aggregate_type";
            tableName: "event_store";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "invoice" | "payment" | "journal_entry" | "account" | "fiscal_year" | "credit_note" | "payroll_run" | "salary_structure" | "employee_advance" | "gst_challan" | "gst_payment" | "gst_return" | "itr_return";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["journal_entry", "account", "fiscal_year", "invoice", "credit_note", "payment", "payroll_run", "salary_structure", "employee_advance", "gst_challan", "gst_payment", "gst_return", "itr_return"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        aggregateId: import("drizzle-orm/pg-core").PgColumn<{
            name: "aggregate_id";
            tableName: "event_store";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        eventType: import("drizzle-orm/pg-core").PgColumn<{
            name: "event_type";
            tableName: "event_store";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "journal_entry_created" | "journal_entry_modified" | "journal_entry_deleted" | "journal_entry_posted" | "journal_entry_voided" | "journal_entry_reversed" | "account_created" | "account_modified" | "account_deactivated" | "fiscal_year_created" | "fiscal_year_closed" | "narration_corrected" | "invoice_created" | "invoice_modified" | "invoice_deleted" | "invoice_posted" | "invoice_voided" | "invoice_sent" | "credit_note_created" | "credit_note_modified" | "credit_note_issued" | "credit_note_voided" | "payment_recorded" | "payment_voided" | "employee_created" | "employee_updated" | "employee_deactivated" | "salary_structure_created" | "salary_structure_updated" | "payroll_processed" | "payroll_finalized" | "payroll_voided" | "payslip_generated" | "advance_given" | "advance_recovered" | "gst_challan_created" | "gst_payment_made" | "itc_reconciled" | "itc_utilized" | "purchase_posted" | "purchase_voided" | "itc_reversed" | "gst_refund_claimed" | "gstr3b_generated" | "income_computed" | "tax_computed" | "itr_generated";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["journal_entry_created", "journal_entry_modified", "journal_entry_deleted", "journal_entry_posted", "journal_entry_voided", "journal_entry_reversed", "account_created", "account_modified", "account_deactivated", "fiscal_year_created", "fiscal_year_closed", "narration_corrected", "invoice_created", "invoice_modified", "invoice_deleted", "invoice_posted", "invoice_voided", "invoice_sent", "credit_note_created", "credit_note_modified", "credit_note_issued", "credit_note_voided", "payment_recorded", "payment_voided", "employee_created", "employee_updated", "employee_deactivated", "salary_structure_created", "salary_structure_updated", "payroll_processed", "payroll_finalized", "payroll_voided", "payslip_generated", "advance_given", "advance_recovered", "gst_challan_created", "gst_payment_made", "itc_reconciled", "itc_utilized", "purchase_posted", "purchase_voided", "itc_reversed", "gst_refund_claimed", "gstr3b_generated", "income_computed", "tax_computed", "itr_generated"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        payload: import("drizzle-orm/pg-core").PgColumn<{
            name: "payload";
            tableName: "event_store";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        sequence: import("drizzle-orm/pg-core").PgColumn<{
            name: "sequence";
            tableName: "event_store";
            dataType: "bigint";
            columnType: "PgBigInt64";
            data: bigint;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        actorId: import("drizzle-orm/pg-core").PgColumn<{
            name: "actor_id";
            tableName: "event_store";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "event_store";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const snapshots: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "snapshots";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "snapshots";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        tenantId: import("drizzle-orm/pg-core").PgColumn<{
            name: "tenant_id";
            tableName: "snapshots";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        aggregateType: import("drizzle-orm/pg-core").PgColumn<{
            name: "aggregate_type";
            tableName: "snapshots";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "invoice" | "payment" | "journal_entry" | "account" | "fiscal_year" | "credit_note" | "payroll_run" | "salary_structure" | "employee_advance" | "gst_challan" | "gst_payment" | "gst_return" | "itr_return";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["journal_entry", "account", "fiscal_year", "invoice", "credit_note", "payment", "payroll_run", "salary_structure", "employee_advance", "gst_challan", "gst_payment", "gst_return", "itr_return"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        aggregateId: import("drizzle-orm/pg-core").PgColumn<{
            name: "aggregate_id";
            tableName: "snapshots";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        sequence: import("drizzle-orm/pg-core").PgColumn<{
            name: "sequence";
            tableName: "snapshots";
            dataType: "bigint";
            columnType: "PgBigInt64";
            data: bigint;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        state: import("drizzle-orm/pg-core").PgColumn<{
            name: "state";
            tableName: "snapshots";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "snapshots";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
//# sourceMappingURL=events.d.ts.map