"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.gstLiabilityLedger = exports.gstItcLedger = exports.gstCashLedger = void 0;
const pg_core_1 = require("drizzle-orm/pg-core");
const enums_1 = require("./enums");
const users_1 = require("./users");
exports.gstCashLedger = (0, pg_core_1.pgTable)("gst_cash_ledger", {
    id: (0, pg_core_1.uuid)("id").defaultRandom().primaryKey(),
    tenantId: (0, pg_core_1.uuid)("tenant_id").notNull(),
    transactionType: (0, enums_1.gstTransactionTypeEnum)("transaction_type").notNull(),
    taxType: (0, enums_1.gstTaxTypeEnum)("tax_type").notNull(),
    amount: (0, pg_core_1.numeric)("amount", { precision: 18, scale: 2 }).notNull(),
    balance: (0, pg_core_1.numeric)("balance", { precision: 18, scale: 2 }).notNull().default("0"),
    transactionDate: (0, pg_core_1.date)("transaction_date").notNull(),
    referenceType: (0, pg_core_1.text)("reference_type"),
    referenceId: (0, pg_core_1.uuid)("reference_id"),
    referenceNumber: (0, pg_core_1.text)("reference_number"),
    challanNumber: (0, pg_core_1.text)("challan_number"),
    challanDate: (0, pg_core_1.date)("challan_date"),
    bankName: (0, pg_core_1.text)("bank_name"),
    narration: (0, pg_core_1.text)("narration"),
    fiscalYear: (0, pg_core_1.text)("fiscal_year").notNull(),
    createdBy: (0, pg_core_1.uuid)("created_by").notNull().references(() => users_1.users.id),
    createdAt: (0, pg_core_1.timestamp)("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
    (0, pg_core_1.index)("gst_cash_ledger_tenant_id_idx").on(table.tenantId),
    (0, pg_core_1.index)("gst_cash_ledger_tax_type_idx").on(table.taxType),
    (0, pg_core_1.index)("gst_cash_ledger_transaction_date_idx").on(table.transactionDate),
    (0, pg_core_1.index)("gst_cash_ledger_fiscal_year_idx").on(table.fiscalYear),
]);
exports.gstItcLedger = (0, pg_core_1.pgTable)("gst_itc_ledger", {
    id: (0, pg_core_1.uuid)("id").defaultRandom().primaryKey(),
    tenantId: (0, pg_core_1.uuid)("tenant_id").notNull(),
    taxType: (0, enums_1.gstTaxTypeEnum)("tax_type").notNull(),
    openingBalance: (0, pg_core_1.numeric)("opening_balance", { precision: 18, scale: 2 }).default("0"),
    itcAvailable: (0, pg_core_1.numeric)("itc_available", { precision: 18, scale: 2 }).default("0"),
    itcReversed: (0, pg_core_1.numeric)("itc_reversed", { precision: 18, scale: 2 }).default("0"),
    itcUtilized: (0, pg_core_1.numeric)("itc_utilized", { precision: 18, scale: 2 }).default("0"),
    closingBalance: (0, pg_core_1.numeric)("closing_balance", { precision: 18, scale: 2 }).default("0"),
    taxPeriodMonth: (0, pg_core_1.text)("tax_period_month").notNull(),
    taxPeriodYear: (0, pg_core_1.text)("tax_period_year").notNull(),
    fiscalYear: (0, pg_core_1.text)("fiscal_year").notNull(),
    sourceDocumentId: (0, pg_core_1.uuid)("source_document_id"),
    sourceDocumentType: (0, pg_core_1.text)("source_document_type"),
    sourceDocumentNumber: (0, pg_core_1.text)("source_document_number"),
    supplierGstin: (0, pg_core_1.text)("supplier_gstin"),
    supplierName: (0, pg_core_1.text)("supplier_name"),
    ineligibleReason: (0, pg_core_1.text)("ineligible_reason"),
    narration: (0, pg_core_1.text)("narration"),
    createdBy: (0, pg_core_1.uuid)("created_by").notNull().references(() => users_1.users.id),
    createdAt: (0, pg_core_1.timestamp)("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: (0, pg_core_1.timestamp)("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
    (0, pg_core_1.index)("gst_itc_ledger_tenant_id_idx").on(table.tenantId),
    (0, pg_core_1.index)("gst_itc_ledger_tax_type_idx").on(table.taxType),
    (0, pg_core_1.index)("gst_itc_ledger_tax_period_idx").on(table.taxPeriodYear, table.taxPeriodMonth),
    (0, pg_core_1.index)("gst_itc_ledger_fiscal_year_idx").on(table.fiscalYear),
]);
exports.gstLiabilityLedger = (0, pg_core_1.pgTable)("gst_liability_ledger", {
    id: (0, pg_core_1.uuid)("id").defaultRandom().primaryKey(),
    tenantId: (0, pg_core_1.uuid)("tenant_id").notNull(),
    taxType: (0, enums_1.gstTaxTypeEnum)("tax_type").notNull(),
    liabilityType: (0, pg_core_1.text)("liability_type").notNull(),
    openingBalance: (0, pg_core_1.numeric)("opening_balance", { precision: 18, scale: 2 }).default("0"),
    taxPayable: (0, pg_core_1.numeric)("tax_payable", { precision: 18, scale: 2 }).default("0"),
    taxPaid: (0, pg_core_1.numeric)("tax_paid", { precision: 18, scale: 2 }).default("0"),
    interestPayable: (0, pg_core_1.numeric)("interest_payable", { precision: 18, scale: 2 }).default("0"),
    interestPaid: (0, pg_core_1.numeric)("interest_paid", { precision: 18, scale: 2 }).default("0"),
    penaltyPayable: (0, pg_core_1.numeric)("penalty_payable", { precision: 18, scale: 2 }).default("0"),
    penaltyPaid: (0, pg_core_1.numeric)("penalty_paid", { precision: 18, scale: 2 }).default("0"),
    closingBalance: (0, pg_core_1.numeric)("closing_balance", { precision: 18, scale: 2 }).default("0"),
    taxPeriodMonth: (0, pg_core_1.text)("tax_period_month").notNull(),
    taxPeriodYear: (0, pg_core_1.text)("tax_period_year").notNull(),
    fiscalYear: (0, pg_core_1.text)("fiscal_year").notNull(),
    sourceDocumentId: (0, pg_core_1.uuid)("source_document_id"),
    sourceDocumentType: (0, pg_core_1.text)("source_document_type"),
    sourceDocumentNumber: (0, pg_core_1.text)("source_document_number"),
    referenceType: (0, pg_core_1.text)("reference_type"),
    referenceId: (0, pg_core_1.uuid)("reference_id"),
    narration: (0, pg_core_1.text)("narration"),
    createdBy: (0, pg_core_1.uuid)("created_by").notNull().references(() => users_1.users.id),
    createdAt: (0, pg_core_1.timestamp)("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: (0, pg_core_1.timestamp)("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
    (0, pg_core_1.index)("gst_liability_ledger_tenant_id_idx").on(table.tenantId),
    (0, pg_core_1.index)("gst_liability_ledger_tax_type_idx").on(table.taxType),
    (0, pg_core_1.index)("gst_liability_ledger_tax_period_idx").on(table.taxPeriodYear, table.taxPeriodMonth),
    (0, pg_core_1.index)("gst_liability_ledger_fiscal_year_idx").on(table.fiscalYear),
]);
//# sourceMappingURL=gst-ledgers.js.map