import { pgTable, uuid, text, numeric, boolean, jsonb, timestamp, uniqueIndex, index, } from "drizzle-orm/pg-core";
import { users } from "./users";
export const gstConfig = pgTable("gst_config", {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    gstin: text("gstin").notNull(),
    legalName: text("legal_name").notNull(),
    tradeName: text("trade_name"),
    registrationDate: timestamp("registration_date", { withTimezone: true }),
    stateCode: text("state_code").notNull(),
    stateName: text("state_name").notNull(),
    businessType: text("business_type").notNull(),
    taxpayerType: text("taxpayer_type").notNull(),
    filingFrequency: text("filing_frequency").notNull(),
    isCompositionDealer: boolean("is_composition_dealer").default(false),
    compositionLimit: numeric("composition_limit", { precision: 18, scale: 2 }),
    aggregateTurnover: numeric("aggregate_turnover", { precision: 18, scale: 2 }).default("0"),
    principalPlaceOfBusiness: text("principal_place_of_business"),
    additionalPlacesOfBusiness: jsonb("additional_places_of_business"),
    authorizedSignatory: text("authorized_signatory"),
    email: text("email"),
    phone: text("phone"),
    mobile: text("mobile"),
    apiCredentials: jsonb("api_credentials"),
    isApiEnabled: boolean("is_api_enabled").default(false),
    lastSyncAt: timestamp("last_sync_at", { withTimezone: true }),
    createdBy: uuid("created_by").notNull().references(() => users.id),
    updatedBy: uuid("updated_by").references(() => users.id),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
    uniqueIndex("gst_config_tenant_id_unique").on(table.tenantId),
    index("gst_config_gstin_idx").on(table.gstin),
]);
export const gstrTableMappings = pgTable("gstr_table_mappings", {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    returnType: text("return_type").notNull(),
    tableNumber: text("table_number").notNull(),
    tableDescription: text("table_description").notNull(),
    accountIds: jsonb("account_ids"),
    taxRate: numeric("tax_rate", { precision: 5, scale: 2 }),
    taxType: text("tax_type"),
    placeOfSupply: text("place_of_supply"),
    isActive: boolean("is_active").default(true),
    createdBy: uuid("created_by").notNull().references(() => users.id),
    updatedBy: uuid("updated_by").references(() => users.id),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
    uniqueIndex("gstr_table_mappings_tenant_return_table_unique").on(table.tenantId, table.returnType, table.tableNumber),
    index("gstr_table_mappings_return_type_idx").on(table.returnType),
]);
//# sourceMappingURL=gst-config.js.map