import { pgTable, uuid, text, numeric, date, timestamp, uniqueIndex, index, } from "drizzle-orm/pg-core";
import { gstReturnTypeEnum, gstReturnStatusEnum } from "./enums";
import { users } from "./users";
export const gstReturns = pgTable("gst_returns", {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    returnNumber: text("return_number").notNull(),
    returnType: gstReturnTypeEnum("return_type").notNull(),
    taxPeriodMonth: text("tax_period_month").notNull(),
    taxPeriodYear: text("tax_period_year").notNull(),
    fiscalYear: text("fiscal_year").notNull(),
    status: gstReturnStatusEnum("status").notNull().default("draft"),
    filingDate: date("filing_date"),
    dueDate: date("due_date").notNull(),
    totalOutwardSupplies: numeric("total_outward_supplies", { precision: 18, scale: 2 }).default("0"),
    totalEligibleItc: numeric("total_eligible_itc", { precision: 18, scale: 2 }).default("0"),
    totalTaxPayable: numeric("total_tax_payable", { precision: 18, scale: 2 }).default("0"),
    totalTaxPaid: numeric("total_tax_paid", { precision: 18, scale: 2 }).default("0"),
    interestAmount: numeric("interest_amount", { precision: 18, scale: 2 }).default("0"),
    penaltyAmount: numeric("penalty_amount", { precision: 18, scale: 2 }).default("0"),
    lateFeeAmount: numeric("late_fee_amount", { precision: 18, scale: 2 }).default("0"),
    arn: text("arn"),
    remarks: text("remarks"),
    createdBy: uuid("created_by").notNull().references(() => users.id),
    filedBy: uuid("filed_by").references(() => users.id),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
    uniqueIndex("gst_returns_tenant_return_type_period_unique").on(table.tenantId, table.returnType, table.taxPeriodMonth, table.taxPeriodYear),
    index("gst_returns_tenant_id_status_idx").on(table.tenantId, table.status),
    index("gst_returns_tenant_id_fiscal_year_idx").on(table.tenantId, table.fiscalYear),
    index("gst_returns_tax_period_idx").on(table.taxPeriodYear, table.taxPeriodMonth),
]);
export const gstReturnLines = pgTable("gst_return_lines", {
    id: uuid("id").defaultRandom().primaryKey(),
    gstReturnId: uuid("gst_return_id").notNull().references(() => gstReturns.id),
    tableNumber: text("table_number").notNull(),
    tableDescription: text("table_description").notNull(),
    transactionType: text("transaction_type").notNull(),
    placeOfSupply: text("place_of_supply").notNull(),
    taxableValue: numeric("taxable_value", { precision: 18, scale: 2 }).notNull().default("0"),
    igstAmount: numeric("igst_amount", { precision: 18, scale: 2 }).default("0"),
    cgstAmount: numeric("cgst_amount", { precision: 18, scale: 2 }).default("0"),
    sgstAmount: numeric("sgst_amount", { precision: 18, scale: 2 }).default("0"),
    cessAmount: numeric("cess_amount", { precision: 18, scale: 2 }).default("0"),
    totalTaxAmount: numeric("total_tax_amount", { precision: 18, scale: 2 }).default("0"),
    sourceDocumentId: uuid("source_document_id"),
    sourceDocumentType: text("source_document_type"),
    sourceDocumentNumber: text("source_document_number"),
    sourceDocumentDate: date("source_document_date"),
    gstin: text("gstin"),
    partyName: text("party_name"),
    remarks: text("remarks"),
}, (table) => [
    index("gst_return_lines_gst_return_id_idx").on(table.gstReturnId),
    index("gst_return_lines_table_number_idx").on(table.tableNumber),
    index("gst_return_lines_source_document_idx").on(table.sourceDocumentId, table.sourceDocumentType),
]);
//# sourceMappingURL=gst-returns.js.map