"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.creditNotes = exports.invoiceLines = exports.invoices = exports.invoiceView = void 0;
const drizzle_orm_1 = require("drizzle-orm");
const pg_core_1 = require("drizzle-orm/pg-core");
const enums_1 = require("./enums");
const users_1 = require("./users");
const accounts_1 = require("./accounts");
exports.invoiceView = (0, pg_core_1.pgTable)("invoice_view", {
    id: (0, pg_core_1.uuid)("id").defaultRandom().primaryKey(),
    tenantId: (0, pg_core_1.uuid)("tenant_id").notNull(),
    invoiceId: (0, pg_core_1.uuid)("invoice_id").notNull(),
    invoiceNumber: (0, pg_core_1.text)("invoice_number").notNull(),
    date: (0, pg_core_1.date)("date").notNull(),
    dueDate: (0, pg_core_1.date)("due_date").notNull(),
    customerName: (0, pg_core_1.text)("customer_name").notNull(),
    customerEmail: (0, pg_core_1.text)("customer_email"),
    customerGstin: (0, pg_core_1.text)("customer_gstin"),
    customerState: (0, pg_core_1.text)("customer_state"),
    status: (0, pg_core_1.text)("status").notNull(),
    subtotal: (0, pg_core_1.numeric)("subtotal", { precision: 18, scale: 2 }).notNull(),
    cgstTotal: (0, pg_core_1.numeric)("cgst_total", { precision: 18, scale: 2 }).notNull(),
    sgstTotal: (0, pg_core_1.numeric)("sgst_total", { precision: 18, scale: 2 }).notNull(),
    igstTotal: (0, pg_core_1.numeric)("igst_total", { precision: 18, scale: 2 }).notNull(),
    discountTotal: (0, pg_core_1.numeric)("discount_total", { precision: 18, scale: 2 }).notNull(),
    grandTotal: (0, pg_core_1.numeric)("grand_total", { precision: 18, scale: 2 }).notNull(),
    fiscalYear: (0, pg_core_1.text)("fiscal_year").notNull(),
    createdBy: (0, pg_core_1.uuid)("created_by").notNull(),
    sentAt: (0, pg_core_1.timestamp)("sent_at", { withTimezone: true }),
    paidAt: (0, pg_core_1.timestamp)("paid_at", { withTimezone: true }),
    pdfUrl: (0, pg_core_1.text)("pdf_url"),
    daysOverdue: (0, pg_core_1.numeric)("days_overdue", { precision: 5, scale: 0 }),
    createdAt: (0, pg_core_1.timestamp)("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: (0, pg_core_1.timestamp)("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
    (0, pg_core_1.uniqueIndex)("invoice_view_tenant_id_invoice_id_unique").on(table.tenantId, table.invoiceId),
    (0, pg_core_1.index)("invoice_view_tenant_id_status_idx").on(table.tenantId, table.status),
    (0, pg_core_1.index)("invoice_view_tenant_id_customer_name_idx").on(table.tenantId, table.customerName),
]);
exports.invoices = (0, pg_core_1.pgTable)("invoices", {
    id: (0, pg_core_1.uuid)("id").defaultRandom().primaryKey(),
    tenantId: (0, pg_core_1.uuid)("tenant_id").notNull(),
    invoiceNumber: (0, pg_core_1.text)("invoice_number").notNull(),
    date: (0, pg_core_1.date)("date").notNull(),
    dueDate: (0, pg_core_1.date)("due_date").notNull(),
    customerName: (0, pg_core_1.text)("customer_name").notNull(),
    customerEmail: (0, pg_core_1.text)("customer_email"),
    customerGstin: (0, pg_core_1.text)("customer_gstin"),
    customerAddress: (0, pg_core_1.text)("customer_address"),
    customerState: (0, pg_core_1.text)("customer_state"),
    status: (0, enums_1.invoiceStatusEnum)("status").notNull().default("draft"),
    subtotal: (0, pg_core_1.numeric)("subtotal", { precision: 18, scale: 2 }).notNull(),
    cgstTotal: (0, pg_core_1.numeric)("cgst_total", { precision: 18, scale: 2 }).notNull(),
    sgstTotal: (0, pg_core_1.numeric)("sgst_total", { precision: 18, scale: 2 }).notNull(),
    igstTotal: (0, pg_core_1.numeric)("igst_total", { precision: 18, scale: 2 }).notNull(),
    discountTotal: (0, pg_core_1.numeric)("discount_total", { precision: 18, scale: 2 }).notNull(),
    grandTotal: (0, pg_core_1.numeric)("grand_total", { precision: 18, scale: 2 }).notNull(),
    currency: (0, pg_core_1.text)("currency").notNull().default("INR"),
    notes: (0, pg_core_1.text)("notes"),
    terms: (0, pg_core_1.text)("terms"),
    fiscalYear: (0, pg_core_1.text)("fiscal_year").notNull(),
    createdBy: (0, pg_core_1.uuid)("created_by").notNull().references(() => users_1.users.id),
    sentAt: (0, pg_core_1.timestamp)("sent_at", { withTimezone: true }),
    paidAt: (0, pg_core_1.timestamp)("paid_at", { withTimezone: true }),
    pdfUrl: (0, pg_core_1.text)("pdf_url"),
    createdAt: (0, pg_core_1.timestamp)("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: (0, pg_core_1.timestamp)("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
    (0, pg_core_1.uniqueIndex)("invoices_tenant_id_invoice_number_unique").on(table.tenantId, table.invoiceNumber),
    (0, pg_core_1.index)("invoices_tenant_id_status_idx").on(table.tenantId, table.status),
    (0, pg_core_1.index)("invoices_tenant_id_customer_name_idx").on(table.tenantId, table.customerName),
    (0, pg_core_1.check)("subtotal_non_negative", (0, drizzle_orm_1.sql) `${table.subtotal} >= 0`),
    (0, pg_core_1.check)("grand_total_non_negative", (0, drizzle_orm_1.sql) `${table.grandTotal} >= 0`),
]);
exports.invoiceLines = (0, pg_core_1.pgTable)("invoice_lines", {
    id: (0, pg_core_1.uuid)("id").defaultRandom().primaryKey(),
    invoiceId: (0, pg_core_1.uuid)("invoice_id").notNull().references(() => exports.invoices.id),
    accountId: (0, pg_core_1.uuid)("account_id").notNull().references(() => accounts_1.accounts.id),
    description: (0, pg_core_1.text)("description").notNull(),
    quantity: (0, pg_core_1.numeric)("quantity", { precision: 10, scale: 2 }).notNull(),
    unitPrice: (0, pg_core_1.numeric)("unit_price", { precision: 18, scale: 2 }).notNull(),
    amount: (0, pg_core_1.numeric)("amount", { precision: 18, scale: 2 }).notNull(),
    gstRate: (0, pg_core_1.numeric)("gst_rate", { precision: 5, scale: 2 }).notNull(),
    cgstAmount: (0, pg_core_1.numeric)("cgst_amount", { precision: 18, scale: 2 }).notNull(),
    sgstAmount: (0, pg_core_1.numeric)("sgst_amount", { precision: 18, scale: 2 }).notNull(),
    igstAmount: (0, pg_core_1.numeric)("igst_amount", { precision: 18, scale: 2 }).notNull(),
    discountPercent: (0, pg_core_1.numeric)("discount_percent", { precision: 5, scale: 2 }).default("0").notNull(),
    discountAmount: (0, pg_core_1.numeric)("discount_amount", { precision: 18, scale: 2 }).default("0").notNull(),
}, (table) => [
    (0, pg_core_1.check)("quantity_non_negative", (0, drizzle_orm_1.sql) `${table.quantity} >= 0`),
    (0, pg_core_1.check)("unit_price_non_negative", (0, drizzle_orm_1.sql) `${table.unitPrice} >= 0`),
    (0, pg_core_1.check)("gst_rate_non_negative", (0, drizzle_orm_1.sql) `${table.gstRate} >= 0`),
]);
exports.creditNotes = (0, pg_core_1.pgTable)("credit_notes", {
    id: (0, pg_core_1.uuid)("id").defaultRandom().primaryKey(),
    tenantId: (0, pg_core_1.uuid)("tenant_id").notNull(),
    invoiceNumber: (0, pg_core_1.text)("invoice_number").notNull(),
    date: (0, pg_core_1.date)("date").notNull(),
    dueDate: (0, pg_core_1.date)("due_date"),
    customerName: (0, pg_core_1.text)("customer_name").notNull(),
    customerEmail: (0, pg_core_1.text)("customer_email"),
    customerGstin: (0, pg_core_1.text)("customer_gstin"),
    customerAddress: (0, pg_core_1.text)("customer_address"),
    customerState: (0, pg_core_1.text)("customer_state"),
    status: (0, enums_1.creditNoteStatusEnum)("status").notNull().default("draft"),
    subtotal: (0, pg_core_1.numeric)("subtotal", { precision: 18, scale: 2 }).notNull(),
    cgstTotal: (0, pg_core_1.numeric)("cgst_total", { precision: 18, scale: 2 }).notNull(),
    sgstTotal: (0, pg_core_1.numeric)("sgst_total", { precision: 18, scale: 2 }).notNull(),
    igstTotal: (0, pg_core_1.numeric)("igst_total", { precision: 18, scale: 2 }).notNull(),
    discountTotal: (0, pg_core_1.numeric)("discount_total", { precision: 18, scale: 2 }).notNull(),
    grandTotal: (0, pg_core_1.numeric)("grand_total", { precision: 18, scale: 2 }).notNull(),
    currency: (0, pg_core_1.text)("currency").notNull().default("INR"),
    notes: (0, pg_core_1.text)("notes"),
    terms: (0, pg_core_1.text)("terms"),
    fiscalYear: (0, pg_core_1.text)("fiscal_year").notNull(),
    createdBy: (0, pg_core_1.uuid)("created_by").notNull().references(() => users_1.users.id),
    originalInvoiceId: (0, pg_core_1.uuid)("original_invoice_id").references(() => exports.invoices.id),
    reason: (0, pg_core_1.text)("reason"),
    createdAt: (0, pg_core_1.timestamp)("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: (0, pg_core_1.timestamp)("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
    (0, pg_core_1.uniqueIndex)("credit_notes_tenant_id_invoice_number_unique").on(table.tenantId, table.invoiceNumber),
    (0, pg_core_1.index)("credit_notes_tenant_id_customer_name_idx").on(table.tenantId, table.customerName),
]);
//# sourceMappingURL=invoices.js.map