// @ts-nocheck
"use client";

import { useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api";

const currentAY = `${new Date().getFullYear() + 1}-${(new Date().getFullYear() + 2).toString().slice(-2)}`;

export default function PaymentHistoryPage() {
  const [assessmentYear, setAssessmentYear] = useState<string>(currentAY);
  const [filterType, setFilterType] = useState<"all" | "advance_tax" | "self_assessment">("all");

  const { data: paymentHistory, isLoading } = api.itrPayment.getPaymentHistory.useQuery({
    assessmentYear,
  });

  const payments = paymentHistory?.payments ?? [];

  const filteredPayments = filterType === "all"
    ? payments
    : payments.filter((p) => p.paymentType === filterType) as any[];

  const handleDownloadChallan = (payment: any) => {
    const content = `
CHALLAN DETAILS
===============

Challan Number: ${payment.challanNumber}
Challan Date: ${payment.challanDate}
Payment Date: ${payment.paidDate}
Payment Type: ${payment.paymentType === "advance_tax" ? `Advance Tax - Installment ${payment.installmentNumber}` : "Self-Assessment Tax"}

Amount: ₹${Number(payment.amount).toLocaleString("en-IN")}

Assessment Year: ${assessmentYear}

---
Generated by ComplianceOS
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${payment.challanNumber}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <Link href="/itr/payment" className="text-sm text-gray-500 hover:underline">
            ← Back to Payment
          </Link>
          <h1 className="text-2xl font-bold mt-1">Payment History</h1>
          <p className="text-sm text-gray-500">Assessment Year: {assessmentYear}</p>
        </div>
        <Link
          href="/itr/payment"
          className="px-4 py-2 bg-blue-600 text-white text-sm rounded hover:bg-blue-700"
        >
          Make Payment
        </Link>
      </div>

      <div className="flex gap-4 items-center flex-wrap">
        <input
          type="text"
          value={assessmentYear}
          onChange={(e) => setAssessmentYear(e.target.value)}
          placeholder="AY (e.g., 2027-28)"
          className="px-3 py-2 border rounded text-sm w-32"
        />

        <select
          value={filterType}
          onChange={(e) => setFilterType(e.target.value as typeof filterType)}
          className="px-3 py-2 border rounded text-sm"
        >
          <option value="all">All Payments</option>
          <option value="advance_tax">Advance Tax Only</option>
          <option value="self_assessment">Self-Assessment Only</option>
        </select>
      </div>

      <div className="bg-white rounded-lg shadow overflow-hidden">
        <div className="px-6 py-4 border-b">
          <h2 className="text-lg font-semibold">Challans</h2>
        </div>
        <table className="w-full text-sm">
          <thead className="bg-gray-50 border-b">
            <tr>
              <th className="px-4 py-3 text-left text-gray-500 font-medium">Payment Type</th>
              <th className="px-4 py-3 text-left text-gray-500 font-medium">Installment</th>
              <th className="px-4 py-3 text-left text-gray-500 font-medium">Challan #</th>
              <th className="px-4 py-3 text-left text-gray-500 font-medium">Challan Date</th>
              <th className="px-4 py-3 text-left text-gray-500 font-medium">Paid Date</th>
              <th className="px-4 py-3 text-right text-gray-500 font-medium">Amount</th>
              <th className="px-4 py-3 text-left text-gray-500 font-medium">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y">
            {isLoading ? (
              <tr>
                <td colSpan={7} className="px-4 py-8 text-center text-gray-500">
                  Loading...
                </td>
              </tr>
            ) : filteredPayments.length > 0 ? (
              filteredPayments.map((payment, idx) => (
                <tr key={payment.id || idx} className="hover:bg-gray-50">
                  <td className="px-4 py-3">
                    <span className={`px-2 py-1 text-xs rounded-full ${
                      payment.paymentType === "advance_tax"
                        ? "bg-blue-100 text-blue-800"
                        : "bg-green-100 text-green-800"
                    }`}>
                      {payment.paymentType === "advance_tax" ? "Advance Tax" : "Self-Assessment"}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-gray-600">
                    {payment.paymentType === "advance_tax" && payment.installmentNumber
                      ? payment.installmentNumber.replace("INSTALLMENT_", "")
                      : "-"}
                  </td>
                  <td className="px-4 py-3">
                    <span className="font-medium text-gray-900">{payment.challanNumber}</span>
                  </td>
                  <td className="px-4 py-3 text-gray-600">{payment.challanDate}</td>
                  <td className="px-4 py-3 text-gray-600">
                    {payment.paidDate ? new Date(payment.paidDate).toLocaleDateString() : "-"}
                  </td>
              <td className="px-4 py-3 text-right font-medium text-gray-900">
                  ₹{(payment.amount as any).toLocaleString("en-IN")}
                  </td>
                  <td className="px-4 py-3">
                    <button
                      onClick={() => handleDownloadChallan(payment)}
                      className="text-blue-600 hover:underline text-xs"
                    >
                      Download
                    </button>
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan={7} className="px-4 py-8 text-center text-gray-500">
                  No payment history yet
                </td>
              </tr>
            )}
          </tbody>
          {filteredPayments.length > 0 && (
            <tfoot className="bg-gray-50 font-medium">
              <tr>
                <td colSpan={5} className="px-4 py-3 text-right text-gray-900">Total:</td>
                <td className="px-4 py-3 text-right text-gray-900">
                  ₹{((paymentHistory?.totalPaid as any) ?? 0).toLocaleString("en-IN")}
                </td>
                <td></td>
              </tr>
            </tfoot>
          )}
        </table>
      </div>

      {filteredPayments.length > 0 && (
        <div className="text-sm text-gray-600">
          Showing {filteredPayments.length} payment(s) for AY {assessmentYear}
        </div>
      )}

      <div className="bg-white rounded-lg shadow p-6">
        <h3 className="font-semibold mb-4">Payment Summary</h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="bg-blue-50 p-4 rounded">
            <p className="text-sm text-gray-500 mb-1">Advance Tax Paid</p>
            <p className="text-xl font-bold text-blue-900">
              ₹{payments.filter((p) => p.paymentType === "advance_tax").reduce((sum, p) => sum + Number(p.amount), 0).toLocaleString("en-IN")}
            </p>
          </div>
          <div className="bg-green-50 p-4 rounded">
            <p className="text-sm text-gray-500 mb-1">Self-Assessment Tax Paid</p>
            <p className="text-xl font-bold text-green-900">
              ₹{payments.filter((p) => p.paymentType === "self_assessment").reduce((sum, p) => sum + Number(p.amount), 0).toLocaleString("en-IN")}
            </p>
          </div>
          <div className="bg-gray-50 p-4 rounded">
            <p className="text-sm text-gray-500 mb-1">Total Paid</p>
            <p className="text-xl font-bold text-gray-900">
              ₹{(((paymentHistory?.totalPaid as any) ?? 0)).toLocaleString("en-IN")}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
